jobs: # A basic unit of work in a run
  setup: 
    # directory where steps are run
    working_directory: ~/ackrep_core
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: cimg/python:3.8
        environment: # environment variables for primary container
          NO_IPS_EXCEPTHOOK: True
          SKIP_TEST_CREATE_PDF: True
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps1--{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependancies
          command: | 
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -e .
      - persist_to_workspace:
          root: ackrep_core 
          paths: 
            - venv
      - save_cache: # cache Python dependencies using checksum of requirements as the cache-key
          key: deps1--{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  import_data:
    working_directory: ~/ackrep_core
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: cimg/python:3.8
    steps:
      - run:
          name: Load Test Data
          command: | 
            cd ../
            ls
            git clone https://github.com/ackrep-org/ackrep_data.git
            mv ackrep_data ackrep_data_for_unittests
            cd ackrep_data_for_unittests
            git checkout for_unittests

               
  test:
    working_directory: ~/ackrep_core
    docker: # run the steps with Docker
      - image: cimg/python:3.8
        environment: # environment variables for primary container
          NO_IPS_EXCEPTHOOK: True
          SKIP_TEST_CREATE_PDF: True
    steps:
      - attach_workspace:
          at: ackrep_core
      - run:
          name: Test Core
          command: | 
            ls
            . venv/bin/activate
            python manage.py makemigrations
            ackrep --bootstrap-test-db
            python manage.py test --keepdb ackrep_core.test.test_core

workflows:
  version: 2 
  build_and_test:
    jobs:
      - setup
      - import_data
      - test:
          requires:
            - setup
            - import_data