# Generated by Django 3.2.10 on 2022-06-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ackrep_web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
