# Generated by Django 3.2.10 on 2022-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ackrep_web", "0002_alter_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="key_str",
            field=models.TextField(default="(unknown key)"),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.TextField(default=""),
        ),
    ]
