# Generated by Django 4.1 on 2022-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ackrep_web", "0007_auto_20220714_2345"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="key_str",
        ),
        migrations.AddField(
            model_name="entity",
            name="uri",
            field=models.TextField(default="(unknown uri)"),
        ),
    ]
